Moviepedia/Controllers/AdminController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Moviepedia.ViewModels;

namespace Moviepedia.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public AdminController(UserManager<IdentityUser> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task<ActionResult> GetUsers()
        {
            var list = new List<UserViewModel>();
            var users = _userManager.Users.ToList();
            foreach (var user in users)
            {
                var roles = await _userManager.GetRolesAsync(user);
                list.Add(new UserViewModel { User = user, Roles = roles });
            }
            return View(list);
        }

        public ActionResult GetRoles(int id)
        {
            return View(_roleManager.Roles.ToList());
        }

        public ActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CreateRole(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("GetRoles");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(name);
        }

        public async Task<IActionResult> EditUserRoles(string Id)
        {
            var user = await _userManager.FindByIdAsync(Id);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var roles = _roleManager.Roles.ToList();
                var model = new ChangeRoleViewModel
                {
                    Id = user.Id,
                    Email = user.Email,
                    AllRoles = roles,
                    UserRoles = userRoles
                };
                return View(model);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> EditUserRoles(string id, List<string> roles)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);
                await _userManager.AddToRolesAsync(user, addedRoles);
                await _userManager.RemoveFromRolesAsync(user, removedRoles);
                return RedirectToAction("GetUsers");
            }
            return NotFound();
        }

        public async Task<IActionResult> DeleteRole(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
                return NotFound();
            var users = await _userManager.GetUsersInRoleAsync(role.Name);
            if (users.Count > 0)
            {
                ViewBag.RoleName = role.Name;
                var list = users.Select(u => u.Email).ToList();
                return View("DeleteError", list);
            }
            return View(role);
        }

        [HttpPost, ActionName("DeleteRole")]
        public async Task<IActionResult> DeleteRoleConfirmed(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
                return NotFound();
            await _roleManager.DeleteAsync(role);
            return RedirectToAction("GetRoles");
        }

        public async Task<IActionResult> DeleteUser(string id)
        {
            if (id == null)
                return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
                return NotFound();
            var roles = await _userManager.GetRolesAsync(user);
            return View(new UserViewModel { User = user, Roles = roles });
        }

        [HttpPost, ActionName("DeleteUser")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (id == null)
                return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
                return NotFound();
            await _userManager.DeleteAsync(user);
            return RedirectToAction("GetUsers");
        }
    }
}

Moviepedia/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Moviepedia.Models;

namespace Moviepedia.Controllers
{
    public class MoviesController : Controller
    {
        private readonly MovieContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public MoviesController(MovieContext context, UserManager<IdentityUser> userManager, 
            SignInManager<IdentityUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        // GET: Movies
        public async Task<IActionResult> Index(int genreId=0, string language="All")
        {
            var movies = new List<Movie>();
            if (genreId > 0)
            {
                var genre = _context.Genres.Where(g => g.Id == genreId).Include(g=>g.Movies).First();
                movies = _context.Movies.Include(m=>m.Genres).Where(m => m.Genres.Contains(genre)).Include(m => m.Reviews).ToList();
            }
            else
            {
                movies = _context.Movies.Include(m=>m.Reviews).ToList();
            }
            if (language!="All")
            {
                movies = movies.Where(m => m.Language == language).ToList();
            }
            ViewBag.GenresList = GetGenres();
            ViewBag.LanguageList = GetLanguages();
            ViewBag.Searched = false;
            return View(movies);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Movies == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.Include(m=>m.Genres).Include(m=>m.Reviews)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }
            if (movie.Reviews == null || movie.Reviews.ToList().Count == 0)
                ViewBag.HasReview = false;
            else
            {
                ViewBag.HasReview = true;
            }
            return View(movie);
        }

        private SelectList GetGenres()
        {
            var genres = _context.Genres.ToList();
            genres.Insert(0, new Genre { Name = "All", Id = 0 });
            var list = new SelectList(genres, "Id", "Name");
            return list;
        }

        private SelectList GetLanguages()
        {
            var movies = _context.Movies.ToList();
            var languages = new HashSet<string>
            {
                "All"
            };
            foreach (var movie in movies)
                languages.Add(movie.Language);
            var list = new SelectList(languages);
            return list;
        }
        [Authorize(Roles = "user")]
        public async Task<IActionResult> GetReviews()
        {
            var userName = HttpContext.User.Identity.Name;
            var user = await _userManager.FindByNameAsync(userName);
            var reviews = await _context.Reviews.Where(r=>r.UserId==user.Id).Include(r=>r.Movie).ToListAsync();
            return View(reviews);
        }

        public async Task<ActionResult> AddReview(int? id)
        {
            if (_signInManager.IsSignedIn(HttpContext.User))
            {
                if (id == null)
                    return NotFound();

                var movie = await _context.Movies.Include(m => m.Reviews).FirstOrDefaultAsync(m => m.Id == id);

                if (movie == null)
                    return NotFound();

                ViewBag.Movie = movie;

                return View();
            }
            return RedirectToAction("SignIn", "Account");
        }

        [HttpPost]
        public async Task<ActionResult> AddReview([Bind("MovieId,Rating,Text")] Review review)
        {
            if (!ModelState.IsValid)
            {
                var name = HttpContext.User.Identity.Name;
                var user = await _userManager.FindByNameAsync(name);
                review.UserId=user.Id;
                _context.Add(review);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", new {id = review.MovieId});
            }
            return View();
        }
        [Authorize(Roles = "user")]
        public async Task<IActionResult> DeleteReview(int id)
        {
            var review = _context.Reviews.ToList().Find(m => m.Id == id);
            if (review != null)
            {
                _context.Reviews.Remove(review);
                _context.SaveChanges();
                return RedirectToAction(nameof(GetReviews));
            }
            return NotFound();
        }
        public IActionResult Search(string searchString)
        {
            var results = new List<Movie>();
            if (!string.IsNullOrEmpty(searchString))
            {
                var rg = new Regex(@"\w+", RegexOptions.IgnoreCase);
                var matches = rg.Matches(searchString.ToLower());
                foreach (var word in matches)
                {
                    int.TryParse(word.ToString(), out int number);
                    var list = _context.Movies.Include(m => m.Reviews).Where(m => m.Director.Contains(word.ToString()) ||
                                                    m.Name.Contains(word.ToString()) || m.Year==number).ToList();
                    results.AddRange(list);
                }
                results = (from item in results select item).Distinct().ToList();
                ViewBag.Searched = true;

                if (results.Count > 0)
                {
                    ViewBag.Msg = "Search results for " + "\"" + searchString + "\":";
                }
                else
                {
                    ViewBag.Msg = "We couldn't find any matches for " +
                        "\"" + searchString + "\"";
                    ViewBag.Msg2 = "Try another search?";
                }
            }
            else
            {
                ViewBag.Searched = false;
                results = _context.Movies.Include(m=>m.Reviews).ToList();
            }    
            ViewBag.GenresList = GetGenres();
            ViewBag.LanguageList = GetLanguages();
            return View("Index", results);
        }
    }
}

Moviepedia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" style="height:100%">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Moviepedia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Moviepedia.styles.css" asp-append-version="true" />
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <style>
        body {
            font-family: 'Montserrat';
            height:100vh;
        }
    </style>
</head>
<body class="bg-dark text-info">
    <header>
        <partial name="_NavbarPartial"/>
    </header>
    <div class="container-fluid" style="min-height:80vh;">
        <main role="main" style="min-height:80vh">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Moviepedia/Views/Shared/_NavbarPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    if (SignInManager.IsSignedIn(User))
    {
        var userName = UserManager.GetUserName(User);
        var user = await UserManager.FindByNameAsync(userName);


        if (user != null && await UserManager.IsInRoleAsync(user, "admin"))
        {
            <nav class="navbar navbar-expand-sm fixed-top bg-dark bg-gradient">
                <div class="container-fluid" >
                    <a class="navbar-brand text-info" asp-action="Index" asp-controller="Movies">
                        <img src="@Url.Content("~/Images/logo.png")" width="25" height="25" class="d-inline-block align-text-top">
                        Moviepedia
                    </a>
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <div class="dropdown">
                                <button class="btn btn-outline-info dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="dropdownOpener">
                                    @UserManager.GetUserName(User)
                                </button>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownOpener">
                                    <li><a class="dropdown-item" asp-controller="Admin" asp-action="GetUsers">Users</a></li>
                                    <li><a class="dropdown-item" asp-controller="Admin" asp-action="GetRoles">Roles</a></li>
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="ChangePassword" asp-route-name="@UserManager.GetUserName(User)">Change password</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li>
                                        <form asp-action="SignOut" asp-controller="Account">
                                            <button type="submit" class="dropdown-item">
                                                Sign out
                                            </button>
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        }
        else if (user != null && await UserManager.IsInRoleAsync(user, "manager"))
        {
            <nav class="navbar navbar-expand-sm  fixed-top bg-dark bg-gradient">
                <div class="container-fluid">
                    <a class="navbar-brand text-info" asp-action="Index" asp-controller="Movies">
                        <img src="@Url.Content("~/Images/logo.png")" width="25" height="25" class="d-inline-block align-text-top">
                        Moviepedia
                    </a>
                    <form asp-action="Search" asp-controller="Movies" class="d-flex" role="search" style="width:30%">
                        <input class="form-control me-2 border-info" type="search" placeholder="Search" name="searchString" aria-label="Search">
                        <button class="btn btn-outline-info" type="submit">Search</button>
                    </form>
                    <ul class="navbar-nav  navbar-right">
                        <li class="nav-item dropdown">
                            <div class="dropdown">
                                <button class="btn btn-outline-info dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="dropdownOpener">
                                    @UserManager.GetUserName(User)
                                </button>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownOpener">
                                    <li><a class="dropdown-item" asp-controller="Manager" asp-action="GetMovies">Movies</a></li>
                                    <li><a class="dropdown-item" asp-controller="Manager" asp-action="GetGenres">Genres</a></li>
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="ChangePassword" asp-route-name="@UserManager.GetUserName(User)">Change password</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li>
                                        <form asp-action="SignOut" asp-controller="Account">
                                            <button type="submit" class="dropdown-item">
                                                Sign out
                                            </button>
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        }
        else
        {
            <nav class="navbar navbar-expand-sm  fixed-top bg-dark bg-gradient">
                <div class="container-fluid">
                    <a class="navbar-brand text-info" asp-action="Index" asp-controller="Movies">
                        <img src="@Url.Content("~/Images/logo.png")" width="25" height="25" class="d-inline-block align-text-top">
                        Moviepedia
                    </a>
                    <form asp-action="Search" asp-controller="Movies" class="d-flex" role="search" style="width:30%">
                        <input class="form-control me-2 border-info" type="search" placeholder="Search" name="searchString" aria-label="Search">
                        <button class="btn btn-outline-info" type="submit">Search</button>
                    </form>
                    <ul class="navbar-nav navbar-right">
                        <li class="nav-item dropdown">
                            <div class="dropdown">
                                <button class="btn btn-outline-info dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="dropdownOpener">
                                    @UserManager.GetUserName(User)
                                </button>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownOpener">
                                    <li><a class="dropdown-item" asp-controller="Movies" asp-action="GetReviews" >My reviews</a></li>
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="ChangePassword" asp-route-name="@UserManager.GetUserName(User)">Change password</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li>
                                        <form asp-action="SignOut" asp-controller="Account">
                                            <button type="submit" class="dropdown-item">
                                                Sign out
                                            </button>
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>

                </div>
            </nav>
        }
    }
    else
    {
        <nav class="navbar navbar-expand-sm fixed-top bg-dark bg-gradient">
            <div class="container-fluid">
                <a class="navbar-brand text-info" asp-action="Index" asp-controller="Movies">
                    <img src="@Url.Content("~/Images/logo.png")" width="25" height="25" class="d-inline-block align-text-top">
                    Moviepedia
                </a>
                <form asp-action="Search" asp-controller="Movies" class="d-flex" role="search" style="width:30%">
                    <input class="form-control me-2 border-info" type="search" placeholder="Search" name="searchString" aria-label="Search">
                    <button class="btn btn-outline-info" type="submit">Search</button>
                </form>
                <a class="btn btn-outline-info" asp-action="SignIn" asp-controller="Account">
                    Sign in
                </a>

            </div>
        </nav>
    }

}