Moviepedia/ViewModels/EditGenresViewModel.cs
using Moviepedia.Models;

namespace Moviepedia.ViewModels
{
    public class EditGenresViewModel
    {
        public IEnumerable<Genre> Genres { get; set; }
        public IEnumerable<Genre> MovieGenres { get; set; }
        public int Id { get; set; }
    }
}

Moviepedia/Controllers/ManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Moviepedia.Models;
using Moviepedia.ViewModels;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;

namespace Moviepedia.Controllers
{
    [Authorize(Roles = "manager")]
    public class ManagerController : Controller
    {
        private readonly MovieContext _context;
        readonly IWebHostEnvironment _environment;

        public ManagerController(MovieContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        public async Task<IActionResult> GetMovies()
        {

              return _context.Movies != null ? 
                          View(await _context.Movies.ToListAsync()) :
                          Problem("Entity set 'MovieContext.Movies'  is null.");

        }

        public IActionResult CreateMovie()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateMovie([Bind("Id,Name,Director,Year,Language,Rating")] Movie movie,
             IFormFile upload)
        {
            if (upload!=null)
            {
                string fileName = Path.GetFileName(upload.FileName);
                if (CheckByGraphicsFormat(fileName))
                {
                    Save(upload, fileName);
                    movie.ImageUrl = fileName;
                }
            }
            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(GetMovies));
            }
            return View(movie);
        }

        public IActionResult EditMovie(int? id)
        {
            if (id == null)
                return NotFound();
            var movie = _context.Movies.ToList().Find(m=>m.Id == id);
            if (movie == null)
                return NotFound();
            return View(movie);
        }

        [HttpPost]
        public IActionResult EditMovie(int id, [Bind("Id,Name,Director,Year,Language")] Movie movie, 
            IFormFile upload)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                if (upload != null)
                {
                    string fileName = System.IO.Path.GetFileName(upload.FileName);
                    if (CheckByGraphicsFormat(fileName))
                    {
                        Save(upload, fileName);
                        movie.ImageUrl = fileName;
                    }
                }
                try
                {
                    _context.Update(movie);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(GetMovies));
            }
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            return View(movie);
        }

        public IActionResult EditGenres(int? id)
        {
            if (id == null)
                return NotFound();
            var movie = _context.Movies.Include(m=>m.Genres).ToList().Find(m => m.Id == id);
            if (movie == null)
                return NotFound();
            var movieGenres = movie.Genres.ToList();
            var genres = _context.Genres.ToList();
            var model = new EditGenresViewModel
            {
                Genres = genres,
                MovieGenres = movieGenres,
                Id = movie.Id
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult EditGenres(int id, List<string> genres)
        {
            var movie = _context.Movies.Include(m=>m.Genres).ToList().Find(m => m.Id == id);
            if (movie != null)
            {
                var newGenres = new List<Genre>();
                foreach(var name in genres)
                {
                    var genre = _context.Genres.ToList().Find(g => g.Name == name);
                    newGenres.Add(genre);
                }
                movie.Genres = newGenres;
                _context.SaveChanges();
                return RedirectToAction("GetMovies");
            }
            return NotFound();
        }

        public async Task<IActionResult> DeleteMovie(int? id)
        {
            if (id == null || _context.Movies == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        [HttpPost, ActionName("DeleteMovie")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteMovieConfirmed(int id)
        {
            if (_context.Movies == null)
            {
                return Problem("Entity set 'MovieContext.Movies'  is null.");
            }
            var movie = await _context.Movies.FindAsync(id);
            if (movie != null)
            {
                _context.Movies.Remove(movie);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(GetMovies));
        }

        public async Task<IActionResult> GetGenres()
        {

            return _context.Genres != null ?
                        View(await _context.Genres.ToListAsync()) :
                        Problem("Entity set 'MovieContext.Genres'  is null.");

        }

        public IActionResult CreateGenre()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateGenre([Bind("Id,Name")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(GetGenres));
            }
            return View(genre);
        }

        public async Task<IActionResult> DeleteGenre(int? id)
        {
            if (id == null || _context.Genres == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres
                .FirstOrDefaultAsync(g => g.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        [HttpPost, ActionName("DeleteGenre")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteGenreConfirmed(int id)
        {
            if (_context.Genres == null)
            {
                return Problem("Entity set 'MovieContext.Genres'  is null.");
            }
            var genre = await _context.Genres.FindAsync(id);
            if (genre != null)
            {
                _context.Genres.Remove(genre);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(GetGenres));
        }


        private bool MovieExists(int id)
        {
          return (_context.Movies?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private static bool CheckByGraphicsFormat(string fileName)
        {
            var ext = fileName[^3..];
            return string.CompareOrdinal(ext, "png") == 0 || string.CompareOrdinal(ext, "jpg") == 0;
        }

        private void Save(IFormFile upload, string fileName)
        {
            Bitmap image = new(upload.OpenReadStream());
            int width = 628;
            int height = 913;
            var smallImage = Resize(image, width, height);
            string path = "\\wwwroot\\Images\\" + fileName;
            var root = _environment.ContentRootPath;
            path = root + path;
            // сохраняем файл в папку  в каталоге wwwroot
            using var fileStream = new FileStream(path, FileMode.Create);
            smallImage.Save(fileStream, ImageFormat.Jpeg);
        }

        private static Bitmap Resize(Image image, int width, int height)
        {
            var destRect = new Rectangle(0, 0, width, height);
            var destImage = new Bitmap(width, height);

            destImage.SetResolution(image.HorizontalResolution, image.VerticalResolution);

            using (var graphics = Graphics.FromImage(destImage))
            {
                graphics.CompositingMode = CompositingMode.SourceCopy;
                graphics.CompositingQuality = CompositingQuality.HighQuality;
                graphics.InterpolationMode = InterpolationMode.HighQualityBicubic;
                graphics.SmoothingMode = SmoothingMode.HighQuality;
                graphics.PixelOffsetMode = PixelOffsetMode.HighQuality;
                using var wrapMode = new ImageAttributes();
                wrapMode.SetWrapMode(WrapMode.TileFlipXY);
                graphics.DrawImage(image, destRect, 0, 0, image.Width, image.Height, GraphicsUnit.Pixel, wrapMode);
            }
            return destImage;
        }
    }
}

Moviepedia/Views/Manager/CreateGenre.cshtml
@model Moviepedia.Models.Genre

<div class="row" style="position:absolute; margin-left:35vw; margin-top:40vh">
    <div class="col-md-4">
        <form asp-action="CreateGenre" style="min-width:30vw">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label h3"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-info" />
            </div>
            <br />
            <a asp-action="GetGenres" class="btn btn-outline-info">Back to list </a>
        </form>
    </div>
</div>

Moviepedia/Views/Manager/CreateMovie.cshtml
@model Moviepedia.Models.Movie

<div class="row" style="position:absolute; margin-left:35vw; margin-top:25vh">
    <div class="col-md-4">
        <form asp-action="CreateMovie" enctype="multipart/form-data" method="post" style="min-width:30vw">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Director" class="control-label"></label>
                <input asp-for="Director" class="form-control" />
                <span asp-validation-for="Director" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Language" class="control-label"></label>
                <input asp-for="Language" class="form-control" />
                <span asp-validation-for="Language" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Выберите файл для загрузки </label>
                <input type="file" name="upload" class="form-control" />
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-info" />
            </div>
            <br />
            <a asp-action="GetMovies" class="btn btn-outline-info">Back to list </a>
        </form>
    </div>
</div>

Moviepedia/Views/Manager/DeleteGenre.cshtml
@model Moviepedia.Models.Genre

<div style="position:absolute; margin-top:30vh; margin-left:30vw">
    <h3>Are you sure you want to delete this?</h3>
    <br />
    <div>
        <dl class="row" style="font-size:22px">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>

        <form asp-action="DeleteGenre" method="post">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Yes" class="btn btn-outline-info" /> |
            <a asp-action="GetGenres" class="btn btn-outline-info">Back to list</a>
        </form>
    </div>
</div>

Moviepedia/Views/Manager/DeleteMovie.cshtml
@model Moviepedia.Models.Movie

<div style="position:absolute; margin-top:30vh; margin-left:30vw">
    <h3>Are you sure you want to delete this?</h3>
    <br />
    <div>
        <dl class="row" style="font-size:22px">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Director)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Director)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Year)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Year)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Language)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Language)
            </dd>
        </dl>

        <form asp-action="DeleteMovie" method="post">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Yes" class="btn btn-outline-info" /> 
            <br />
            <a asp-action="GetMovies" class="btn btn-outline-info" style="margin-top:3vh">Back to list</a>
        </form>
    </div>
</div>

Moviepedia/Views/Manager/EditGenres.cshtml
@model Moviepedia.ViewModels.EditGenresViewModel

<div style="display:flex; flex-flow:column; height:100%; width:100%; position:absolute; right:0; left:0;">
    <form asp-action="EditGenres" asp-controller="Manager" method="post" style="margin:auto; font-size:22px">
        <input type="hidden" name="id" value="@Model.Id" />
        <div class="form-check">
            <label class="form-check-label h3">Genres</label>
            <br />
            @foreach (var genre in Model.Genres)
            {
                if (Model.MovieGenres.Contains(genre))
                {
                    <input type="checkbox" class="form-check-input" name="genres" value="@genre.Name" checked /> @genre.Name
                    <br />
                }
                else
                {
                    <input type="checkbox" class="form-check-input" name="genres" value="@genre.Name" /> @genre.Name
                    <br />
                }
            }
        </div>
        <br />
        <input type="submit" value="Confirm" class="btn btn-outline-info"/>
        <a asp-action="GetMovies" asp-controller="Manager" class="btn btn-outline-info">Back</a>
    </form>
</div>

Moviepedia/Views/Manager/EditMovie.cshtml
@using System.Linq
@model Moviepedia.Models.Movie

<!DOCTYPE html>


    <div class="row" style="position:absolute; margin-top:30vh; margin-left:20vw; font-size:24px">
            <form asp-action="EditMovie" method="post" enctype="multipart/form-data" style="display:flex; justify-content:space-around; min-width:50vw" >
                <div>
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Director" class="control-label"></label>
                        <input asp-for="Director" class="form-control" />
                        <span asp-validation-for="Director" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Year" class="control-label"></label>
                        <input asp-for="Year" class="form-control" />
                        <span asp-validation-for="Year" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Language" class="control-label"></label>
                        <input asp-for="Language" class="form-control" />
                        <span asp-validation-for="Language" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Image </label>
                        <input type="hidden" asp-for="ImageUrl" />       
                        <input type="file" name="upload" class="form-control" />
                    </div>
                    <br />
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-outline-info" />
                    </div>
                    <br />
                    <a asp-action="GetMovies" class="btn btn-outline-info">Back to List</a>
                </div>
            </form>
    </div>
    

Moviepedia/Views/Manager/GetGenres.cshtml
@using Moviepedia.Models
@using System.Linq
@model IEnumerable<Moviepedia.Models.Genre>


<!DOCTYPE html>
<div style="position:absolute; margin-top:8vh; margin-left:35vw">
    
<table class="table text-info border-info h3" style="margin-top:3vh; max-width:40vw" >
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@for (int i=0;i<Model.Count();i+=2) {
        <tr>
            <td>
                @Model.ToArray()[i].Name
            </td>
            <td style="text-align:right">
                <a asp-action="DeleteGenre" asp-route-id="@Model.ToArray()[i].Id">
                    <img src="@Url.Content("~/Images/delete.png")" width="30px" >
                </a>
            </td>
                    @if (i + 1 < Model.Count())
                    {
                        <td>
                            @Model.ToArray()[i+1].Name
                        </td>
                        <td style="text-align:right">
                            <a asp-action="DeleteGenre" asp-route-id="@Model.ToArray()[i].Id">
                                <img src="@Url.Content("~/Images/delete.png")" width="30px">
                            </a>
                        </td>
                    }
        </tr>
}
    </tbody>
</table>
<p style="margin-top:2vh">
    <a asp-action="CreateGenre" class="btn btn-outline-info">Add new genre</a>
    </p>
</div>

Moviepedia/Views/Manager/GetMovies.cshtml
@model IEnumerable<Moviepedia.Models.Movie>

<!DOCTYPE html>


<p style="margin-top:10vh">
    <a asp-action="CreateMovie" class="btn btn-outline-info">Add new movie</a>
</p>
<table class="table text-info border-info" style="margin-top:3vh" >
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Director)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Language)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Director)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Language)
            </td>
            <td style="text-align:right">
                <a asp-action="EditMovie" class="btn btn-outline-info" asp-route-id="@item.Id">Edit</a> 
                <a asp-action="EditGenres" class="btn btn-outline-info" asp-route-id="@item.Id">Edit genres</a> 
                <a asp-action="DeleteMovie" class="btn btn-outline-info" asp-route-id="@item.Id">
                    Delete
                </a>
            </td>
        </tr>
}
    </tbody>
</table>